### PR TITLE
Pub 865

### PR DESCRIPTION
**Pull request by marcogagliardi**
**Before creating a pull request make sure that:**

- [ ] commit messages are meaningful and follow good commit message guidelines
- [ ] README and other documentation has been updated / added (if needed)
- [ ] tests have been updated / new tests has been added (if needed)

Please remove this line and everything above and fill the following sections:

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/PUB-865

### Change description ###

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by kurt-uk — APPROVED** [review]

**Review by junaidiqbalmoj — APPROVED** [review]

**Comment by kurt-uk** [comment]
done some investigation for you and it looks like its the date thats messing things up

**Comment by kurt-uk** [comment]
done some investigation for you and it looks like its the date on some thats messing things up

**Comment by kurt-uk** [comment]
do we need this now @marcogagliardi? if not please try keep the repositories tidy

**Comment by kurt-uk** [comment]
@marcogagliardi is this still needed? it looks stale.
please remember to clean up after yourself

**Comment by kurt-uk** [comment]
@marcogagliardi you still have this PR open, if its not needed please close. keep the repos clean

**Comment by marcogagliardi** [comment]
obsolete

**Pull request closed without merging**
